name: Vercel Development Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-development:
    runs-on: ubuntu-latest
    steps:
      # CHECKOUT REPOSITORY
      - uses: actions/checkout@v2

      # INSTALL NODE.JS AND PNPM
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install pnpm
        run: npm install -g pnpm

      # SET UP PNPM GLOBAL BIN DIRECTORY
      - name: Set up pnpm global bin directory
        run: pnpm setup

      # ADD PNPM TO PATH
      - name: Add pnpm to PATH
        run: echo "export PATH=$(pnpm bin):\$PATH" >> $GITHUB_ENV

      # INSTALL DEPENDENCIES WITH PNPM
      - name: Install dependencies
        run: pnpm install

      # INSTALL VERCEL CLI WITH PNPM
      - name: Install Vercel CLI
        run: pnpm add -g vercel@latest

      # PULL VERCEL ENVIRONMENT INFORMATION
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}

      # BUILD PROJECT ARTIFACTS
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      # DEPLOY PROJECT ARTIFACTS TO VERCEL
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
